from enum import Enum


class Docfield(Enum):
    """
    The formula is, if the Docfield just 3 chars like Int then it will be int, if more than 3 characters then First character + 2 Second characters,
    example Data will be d + at = dat.
    """

    Data = "dta"
    Link = "lnk"
    DynamicLink = "dnk"
    Check = "cck"
    Select = "sct"
    Table = "tle"
    Attach = "ach"
    AttachImage = "age"
    TextEditor = "tor"
    Date = "dte"
    DateAndTime = "dme"
    Barcode = "bde"
    Button = "bon"
    Code = "cde"
    Color = "cor"
    ColumnBreak = "cak"
    Currency = "ccy"
    Float = "fat"
    Geolocation = "gon"
    HTML = "hml"
    Image = "ige"
    Int = "int"
    SmallText = "sxt"
    LongText = "lxt"
    Text = "txt"
    MarkdownEditor = "mor"
    Password = "prd"  # nosec
    Percent = "pnt"
    Rating = "rng"
    ReadOnly = "rly"
    SectionBreak = "sak"
    TabBreak = "tak"
    Signature = "sre"
    TableMultiselect = "tct"
    Time = "tme"
    Duration = "don"
    JSON = "jon"
